spring:
  datasource:
    driver-class-name: @datasource.driver-class-name@
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
#  servlet:
#    multipart:
#      max-file-size: ${ai.life.servlet.multipart.max-file-size}
#      max-request-size: ${ai.life.servlet.multipart.max-request-size}
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
aliyun:
  oss:
    endpoint: @aliyun.oss.endpoint@
    OSS_ACCESS_KEY_ID: @aliyun.oss.OSS_ACCESS_KEY_ID@
    OSS_ACCESS_KEY_SECRET: @aliyun.oss.OSS_ACCESS_KEY_SECRET@
    bucketName: @aliyun.oss.bucketName@
logging:
  level:
     com:
      life:
        ai:
          mapper: debug
          service: info
          controller: info
life:
  ai:
    jwt:
      admin-secret-key: @jwt.admin-secret-key@
      admin-ttl: @jwt.admin-ttl@
      admin-token-name: @jwt.admin-token-name@

      user-secret-key: @jwt.user-secret-key@
      user-ttl: @jwt.user-ttl@
      user-token-name: @jwt.user-token-name@

    wechat:
      appid: @wechat.appid@
      secret: @wechat.secret@

redis:
  host: @redis.host@
  post: @redis.post@
  password: @redis.password@
  database: @redis.database@