ai:
  life:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ai_life
      username: root
      password: cfwrettt.com
#    servlet:
#      multipart:
#        max-file-size: 10MB
#        max-request-size: 100MB

    aliyun:
      oss:
        endpoint: https://oss-cn-beijing.aliyuncs.com
        OSS_ACCESS_KEY_ID:
        OSS_ACCESS_KEY_SECRET:
        bucketName: web-tianci
    jwt:
      admin-secret-key: litianciskey
      admin-ttl: 6000000
      admin-token-name: token

      user-secret-key: litianciskey
      user-ttl: 6000000
      user-token-name: authentication

    wechat:
      appid:
      secret:

    redis:
      host: localhost
      post: 6379
      password: 123456
      database: 1